### ISSUE TITLE
ChamferDistancePytorch not included

### ISSUE THREAD

**Issue by FarisHijazi** [junzhezhang/mesh-inversion#1]
hi, I'm trying to reproduce results and also play around with the model, but I wasn't able to get it to run

the `run_inversion.py` expects `lib/external/` to exist, but it does not, the .gitignore actually ignores it completely. I tried cloning the [ChamferDistancePytorch](https://github.com/ThibaultGROUEIX/ChamferDistancePytorch) repository but it is missing `distChamfer_downsample`, could you please share your version so that we could get the model working

Thanks in advanced! and thanks for sharing the pretrained model

**Comment by junzhezhang** [comment]
@FarisHijazi Hi, thanks for your interest in our work. I have just included it in `lib/external`, please check it out.

Best,
Junzhe

**Comment by FarisHijazi** [comment]
Btw forgot to say thank, it is working 👌
