### ISSUE TITLE
About env

### ISSUE THREAD

**Issue by kkyi10** [junzhezhang/mesh-inversion#2]
Hello, thank you very much for your excellent work, but when I installing kaolin, it mentioned PyTorch >=1.2, <1.5 ，but it is required in your env mentioned PyTorch=1.11 and cuda=11.3. This seems a bit contradictory. Besides, kaolin now supports 0.9 version. I wonder what version of kaolin you installed? Looking forward to your reply, thank you very much!

**Comment by junzhezhang** [comment]
Hi, 

Thanks for your interest in our work. For the kaolin version, I installed from commit [e7e5131](https://github.com/NVIDIAGameWorks/kaolin/tree/e7e513173bd4159ae45be6b3e156a3ad156a3eb9). Note that version 0.9 may have different APIs compared to what I used in the codebase. For the pytorch and cuda version, it should very flex, you can install pytorch 1.4 as well, with compatible cuda version. 

Thanks,
Junzhe

**Comment by kkyi10** [comment]
I got it. Thank you very much for your reply :)
