### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by Fatalite** [junzhezhang/mesh-inversion#3]
Thank you for great codes.
But I faced with memory error
My PC has GTX 1050ti (2Gb)
Can you answer Any idea to deal with this problem?

**Comment by junzhezhang** [comment]
Hi, can you share more details please?

**Comment by Fatalite** [comment]
I already formatted my sub PC(1050Ti,2gb). 
So I can't reproduce that error, 
but, I finally can execute mesh-inversion with Main PC(2070super,6Gb). 
So I think this problem occurs by low GPU ram.
Thank you for your attention for a stupid undergraduate
