### ISSUE TITLE
Solving environment: failed  ResolvePackageNotFound:

### ISSUE THREAD

**Issue by dellshan** [junzhezhang/mesh-inversion#7]
Solving environment: failed

ResolvePackageNotFound: 
  - giflib==5.2.1=h7b6447c_0
  - portalocker==2.4.0=py37h89c1867_0
  - importlib-metadata==4.11.3=py37h89c1867_1
  - libwebp-base==1.2.2=h7f8727e_0
  - gnutls==3.6.15=he1e5248_0
  - readline==8.1.2=h7f8727e_1
  - future==0.18.2=py37h89c1867_5
  - python==3.7.13=h12debd9_0
  - tk==8.6.11=h1ccaba5_0
  - setuptools==61.2.0=py37h06a4308_0
  - brotlipy==0.7.0=py37h27cfd23_1003
  - yaml==0.2.5=h516909a_0
  - zstd==1.4.9=haebb681_0
  - x264==1!161.3030=h7f98852_1
  - nvidiacub==1.10.0=0
  - openh264==2.1.1=h4ff587b_0
  - libgcc-ng==9.3.0=h5101ec6_17
  - intel-openmp==2021.4.0=h06a4308_3561
  - _openmp_mutex==4.5=1_gnu
  - jpeg==9d=h7f8727e_0
  - cryptography==36.0.0=py37h9ce1e76_0
  - freetype==2.11.0=h70c0345_0
  - gmp==6.2.1=h2531618_2
  - mkl_random==1.2.2=py37h51133e4_0
  - libstdcxx-ng==9.3.0=hd4cf53a_17
  - numpy-base==1.21.5=py37hf524024_1
  - certifi==2022.5.18.1=py37h89c1867_0
  - pysocks==1.7.1=py37_1
  - libprotobuf==3.15.8=h780b84a_0
  - libffi==3.3=he6710b0_2
  - c-ares==1.18.1=h7f8727e_0
  - libidn2==2.3.2=h7f8727e_0
  - bzip2==1.0.8=h7b6447c_0
  - libgomp==9.3.0=h5101ec6_17
  - xz==5.2.5=h7b6447c_0
  - ncurses==6.3=h7f8727e_2
  - ca-certificates==2022.5.18.1=ha878542_0
  - sqlite==3.38.2=hc218d9a_0
  - libunistring==0.9.10=h27cfd23_0
  - zlib==1.2.11=h7f8727e_4
  - nettle==3.7.3=hbbd107a_1
  - torchaudio==0.11.0=py37_cu113
  - ld_impl_linux-64==2.35.1=h7274673_9
  - torchvision==0.12.0=py37_cu113
  - libiconv==1.15=h63c8f33_5
  - lcms2==2.12=h3be6417_0
  - openssl==1.1.1o=h7f8727e_0
  - pytorch3d==0.6.2=py37_cu113_pyt1110
  - mkl_fft==1.3.1=py37hd3c417c_0
  - ffmpeg==4.3.2=hca11adc_0
  - cffi==1.15.0=py37hd667e15_1
  - lame==3.100=h7b6447c_0
  - mkl==2021.4.0=h06a4308_640
  - pip==21.2.2=py37h06a4308_0
  - libtasn1==4.16.0=h27cfd23_0
  - libtiff==4.2.0=h85742a9_0
  - mkl-service==2.4.0=py37h7f8727e_0
  - libwebp==1.2.2=h55f646e_0
  - cudatoolkit==11.3.1=h2bc3f7f_2
  - pytorch==1.11.0=py3.7_cuda11.3_cudnn8.2.0_0
  - lz4-c==1.9.3=h295c915_1
  - libpng==1.6.37=hbc83047_0
  - libuv==1.40.0=h7b6447c_0

EnvironmentNameNotFound: Could not find conda environment: mesh_inv
You can list all discoverable environments with `conda info --envs`.

**Comment by dellshan** [comment]
When I run this command from the directory: 
conda env create -f env.yml
conda activate mesh_inv

I get this error above.

**Comment by dellshan** [comment]
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.


PackagesNotFoundError: The following packages are not available from current channels:

  - torch

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by junzhezhang** [comment]
Hi,
`conda env create -f env.yml` may not always work on different environments. I would suggest you to use conda and pip to install the packages on your own in a newly created conda env. The most tricky part is for kaolin installation, which you can refer to convmesh.

Best,
Junzhe

**Comment by dellshan** [comment]
Pip subprocess error:
ERROR: Ignored the following versions that require a different python version: 2023.3.0 Requires-Python >=3.8; 2023.4.0 Requires-Python >=3.8; 4.38.1.dev0 Requires-Python >=3.8; 4.39.0 Requires-Python >=3.8; 4.39.1 Requires-Python >=3.8; 4.39.2 Requires-Python >=3.8; 4.39.3 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement human-det==0.0.2 (from versions: none)
ERROR: No matching distribution found for human-det==0.0.2

failed

CondaEnvException: Pip failed

**Comment by dellshan** [comment]
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/59307288/234191283-1e015d5b-ab4e-4510-96f6-59542fffd2ad.png">

**Comment by dellshan** [comment]
Even on PIP website,  it can find the human-det, then how can you compile that ?

**Comment by dellshan** [comment]
Even on PIP website, it can not  find the human-det, then how can you compile that ?

**Comment by dellshan** [comment]
what is the   - unknown==0.0.0   here ?

**Comment by junzhezhang** [comment]
Hi, you may ignore those that cannot be found. The env.yml file was exported from my original conda env, which may include some unnecessary packages. Thus, you may manually install the necessary packages, one simple shortcut would be install according to [convmesh](https://github.com/dariopavllo/convmesh) code base .

**Comment by dellshan** [comment]
thank you so much for your reminder. It's really helpful.
