### ISSUE TITLE
ModuleNotFoundError: No module named 'kaolin.graphics'.

### ISSUE THREAD

**Issue by mitesuti** [junzhezhang/mesh-inversion#8]
I built the environment as you specified and ran the command

!python run_inversion.py --name author_released --checkpoint_dir pretrained

Then I got the following error

Traceback (most recent call last):.
  File "run_inversion.py", line 12, in <module
    from lib.mesh_inversion import MeshInversion
  File "/content/drive/MyDrive/mesh-inversion/lib/mesh_inversion.py", line 14, in <module>
    from lib.rendering.renderer import Renderer
  File "/content/drive/MyDrive/mesh-inversion/lib/rendering/renderer.py", line 1, in <module>
    from kaolin.graphics.dib_renderer.rasterizer import linear_rasterizer
ModuleNotFoundError: No module named 'kaolin.graphics'.

I don't know what is causing this, do you know how to solve it?
I am using googlecolab.

Also, which file should I put the photos and other files that I want to reconstruct in 3D? It would be great if you could tell me all the file structure as well.

Thank you in advance for your help.

**Comment by mitesuti** [comment]
Resolved, thank you.

**Comment by cuicanyu** [comment]
Hello, I have the same problem. Could you please tell me how to solve it?

**Comment by mitesuti** [comment]
I forget the details, but I think it was because I did not put in the correct branch of kaolin.

I probably could have installed it by doing the following

git clone https://github.com/NVIDIAGameWorks/kaolin.git
cd kaolin

git config --global user.name "(your github username)"
git config --global user.email "(your github email address)"
git init
git branch -a
git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
git fetch origin

git checkout -f e7e513173b

python setup.py install
pip install --no-dependencies nuscenes-devkit opencv-python-headless scikit-learn joblib pyquaternion cachetools
pip install packaging

**Comment by cuicanyu** [comment]
thanks a lot! I will try
